# Generated by Django 3.2.25 on 2025-02-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bespokerequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bespokerequest',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='bespokerequest',
            name='telephonenumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Number'),
        ),
    ]
