# Generated by Django 3.2.25 on 2025-02-07 13:21

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20250206_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
