# Generated by Django 3.2.25 on 2025-01-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='StoreProduct',
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'StoreCategories'},
        ),
    ]
